//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.7905
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 

using WebsitePanel.Providers.Common;
using WebsitePanel.Providers.ResultObjects;
using WebsitePanel.Providers.StorageSpaces;

namespace WebsitePanel.EnterpriseServer {
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="esStorageSpacesSoap", Namespace="http://tempuri.org/")]
    public partial class esStorageSpaces : Microsoft.Web.Services3.WebServicesClientProtocol {
        
        private System.Threading.SendOrPostCallback GetStorageSpaceLevelsPagedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStorageSpaceLevelByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveStorageSpaceLevelOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLevelResourceGroupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveLevelResourceGroupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveStorageSpaceLevelOperationCompleted;
        
        /// <remarks/>
        public esStorageSpaces() {
            this.Url = "http://localhost:9002/esStorageSpaces.asmx";
        }
        
        /// <remarks/>
        public event GetStorageSpaceLevelsPagedCompletedEventHandler GetStorageSpaceLevelsPagedCompleted;
        
        /// <remarks/>
        public event GetStorageSpaceLevelByIdCompletedEventHandler GetStorageSpaceLevelByIdCompleted;
        
        /// <remarks/>
        public event SaveStorageSpaceLevelCompletedEventHandler SaveStorageSpaceLevelCompleted;
        
        /// <remarks/>
        public event GetLevelResourceGroupsCompletedEventHandler GetLevelResourceGroupsCompleted;
        
        /// <remarks/>
        public event SaveLevelResourceGroupsCompletedEventHandler SaveLevelResourceGroupsCompleted;
        
        /// <remarks/>
        public event RemoveStorageSpaceLevelCompletedEventHandler RemoveStorageSpaceLevelCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStorageSpaceLevelsPaged", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StorageSpaceLevelPaged GetStorageSpaceLevelsPaged(string filterColumn, string filterValue, string sortColumn, int startRow, int maximumRows) {
            object[] results = this.Invoke("GetStorageSpaceLevelsPaged", new object[] {
                        filterColumn,
                        filterValue,
                        sortColumn,
                        startRow,
                        maximumRows});
            return ((StorageSpaceLevelPaged)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetStorageSpaceLevelsPaged(string filterColumn, string filterValue, string sortColumn, int startRow, int maximumRows, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetStorageSpaceLevelsPaged", new object[] {
                        filterColumn,
                        filterValue,
                        sortColumn,
                        startRow,
                        maximumRows}, callback, asyncState);
        }
        
        /// <remarks/>
        public StorageSpaceLevelPaged EndGetStorageSpaceLevelsPaged(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((StorageSpaceLevelPaged)(results[0]));
        }
        
        /// <remarks/>
        public void GetStorageSpaceLevelsPagedAsync(string filterColumn, string filterValue, string sortColumn, int startRow, int maximumRows) {
            this.GetStorageSpaceLevelsPagedAsync(filterColumn, filterValue, sortColumn, startRow, maximumRows, null);
        }
        
        /// <remarks/>
        public void GetStorageSpaceLevelsPagedAsync(string filterColumn, string filterValue, string sortColumn, int startRow, int maximumRows, object userState) {
            if ((this.GetStorageSpaceLevelsPagedOperationCompleted == null)) {
                this.GetStorageSpaceLevelsPagedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStorageSpaceLevelsPagedOperationCompleted);
            }
            this.InvokeAsync("GetStorageSpaceLevelsPaged", new object[] {
                        filterColumn,
                        filterValue,
                        sortColumn,
                        startRow,
                        maximumRows}, this.GetStorageSpaceLevelsPagedOperationCompleted, userState);
        }
        
        private void OnGetStorageSpaceLevelsPagedOperationCompleted(object arg) {
            if ((this.GetStorageSpaceLevelsPagedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStorageSpaceLevelsPagedCompleted(this, new GetStorageSpaceLevelsPagedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStorageSpaceLevelById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StorageSpaceLevel GetStorageSpaceLevelById(int id) {
            object[] results = this.Invoke("GetStorageSpaceLevelById", new object[] {
                        id});
            return ((StorageSpaceLevel)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetStorageSpaceLevelById(int id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetStorageSpaceLevelById", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public StorageSpaceLevel EndGetStorageSpaceLevelById(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((StorageSpaceLevel)(results[0]));
        }
        
        /// <remarks/>
        public void GetStorageSpaceLevelByIdAsync(int id) {
            this.GetStorageSpaceLevelByIdAsync(id, null);
        }
        
        /// <remarks/>
        public void GetStorageSpaceLevelByIdAsync(int id, object userState) {
            if ((this.GetStorageSpaceLevelByIdOperationCompleted == null)) {
                this.GetStorageSpaceLevelByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStorageSpaceLevelByIdOperationCompleted);
            }
            this.InvokeAsync("GetStorageSpaceLevelById", new object[] {
                        id}, this.GetStorageSpaceLevelByIdOperationCompleted, userState);
        }
        
        private void OnGetStorageSpaceLevelByIdOperationCompleted(object arg) {
            if ((this.GetStorageSpaceLevelByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStorageSpaceLevelByIdCompleted(this, new GetStorageSpaceLevelByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveStorageSpaceLevel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IntResult SaveStorageSpaceLevel(StorageSpaceLevel level, ResourceGroupInfo[] groups) {
            object[] results = this.Invoke("SaveStorageSpaceLevel", new object[] {
                        level,
                        groups});
            return ((IntResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSaveStorageSpaceLevel(StorageSpaceLevel level, ResourceGroupInfo[] groups, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SaveStorageSpaceLevel", new object[] {
                        level,
                        groups}, callback, asyncState);
        }
        
        /// <remarks/>
        public IntResult EndSaveStorageSpaceLevel(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((IntResult)(results[0]));
        }
        
        /// <remarks/>
        public void SaveStorageSpaceLevelAsync(StorageSpaceLevel level, ResourceGroupInfo[] groups) {
            this.SaveStorageSpaceLevelAsync(level, groups, null);
        }
        
        /// <remarks/>
        public void SaveStorageSpaceLevelAsync(StorageSpaceLevel level, ResourceGroupInfo[] groups, object userState) {
            if ((this.SaveStorageSpaceLevelOperationCompleted == null)) {
                this.SaveStorageSpaceLevelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveStorageSpaceLevelOperationCompleted);
            }
            this.InvokeAsync("SaveStorageSpaceLevel", new object[] {
                        level,
                        groups}, this.SaveStorageSpaceLevelOperationCompleted, userState);
        }
        
        private void OnSaveStorageSpaceLevelOperationCompleted(object arg) {
            if ((this.SaveStorageSpaceLevelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveStorageSpaceLevelCompleted(this, new SaveStorageSpaceLevelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLevelResourceGroups", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResourceGroupInfo[] GetLevelResourceGroups(int id) {
            object[] results = this.Invoke("GetLevelResourceGroups", new object[] {
                        id});
            return ((ResourceGroupInfo[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetLevelResourceGroups(int id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetLevelResourceGroups", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public ResourceGroupInfo[] EndGetLevelResourceGroups(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ResourceGroupInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLevelResourceGroupsAsync(int id) {
            this.GetLevelResourceGroupsAsync(id, null);
        }
        
        /// <remarks/>
        public void GetLevelResourceGroupsAsync(int id, object userState) {
            if ((this.GetLevelResourceGroupsOperationCompleted == null)) {
                this.GetLevelResourceGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLevelResourceGroupsOperationCompleted);
            }
            this.InvokeAsync("GetLevelResourceGroups", new object[] {
                        id}, this.GetLevelResourceGroupsOperationCompleted, userState);
        }
        
        private void OnGetLevelResourceGroupsOperationCompleted(object arg) {
            if ((this.GetLevelResourceGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLevelResourceGroupsCompleted(this, new GetLevelResourceGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveLevelResourceGroups", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultObject SaveLevelResourceGroups(int levelId, ResourceGroupInfo[] newGroups) {
            object[] results = this.Invoke("SaveLevelResourceGroups", new object[] {
                        levelId,
                        newGroups});
            return ((ResultObject)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSaveLevelResourceGroups(int levelId, ResourceGroupInfo[] newGroups, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SaveLevelResourceGroups", new object[] {
                        levelId,
                        newGroups}, callback, asyncState);
        }
        
        /// <remarks/>
        public ResultObject EndSaveLevelResourceGroups(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ResultObject)(results[0]));
        }
        
        /// <remarks/>
        public void SaveLevelResourceGroupsAsync(int levelId, ResourceGroupInfo[] newGroups) {
            this.SaveLevelResourceGroupsAsync(levelId, newGroups, null);
        }
        
        /// <remarks/>
        public void SaveLevelResourceGroupsAsync(int levelId, ResourceGroupInfo[] newGroups, object userState) {
            if ((this.SaveLevelResourceGroupsOperationCompleted == null)) {
                this.SaveLevelResourceGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveLevelResourceGroupsOperationCompleted);
            }
            this.InvokeAsync("SaveLevelResourceGroups", new object[] {
                        levelId,
                        newGroups}, this.SaveLevelResourceGroupsOperationCompleted, userState);
        }
        
        private void OnSaveLevelResourceGroupsOperationCompleted(object arg) {
            if ((this.SaveLevelResourceGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveLevelResourceGroupsCompleted(this, new SaveLevelResourceGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveStorageSpaceLevel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultObject RemoveStorageSpaceLevel(int id) {
            object[] results = this.Invoke("RemoveStorageSpaceLevel", new object[] {
                        id});
            return ((ResultObject)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRemoveStorageSpaceLevel(int id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RemoveStorageSpaceLevel", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public ResultObject EndRemoveStorageSpaceLevel(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ResultObject)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveStorageSpaceLevelAsync(int id) {
            this.RemoveStorageSpaceLevelAsync(id, null);
        }
        
        /// <remarks/>
        public void RemoveStorageSpaceLevelAsync(int id, object userState) {
            if ((this.RemoveStorageSpaceLevelOperationCompleted == null)) {
                this.RemoveStorageSpaceLevelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveStorageSpaceLevelOperationCompleted);
            }
            this.InvokeAsync("RemoveStorageSpaceLevel", new object[] {
                        id}, this.RemoveStorageSpaceLevelOperationCompleted, userState);
        }
        
        private void OnRemoveStorageSpaceLevelOperationCompleted(object arg) {
            if ((this.RemoveStorageSpaceLevelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveStorageSpaceLevelCompleted(this, new RemoveStorageSpaceLevelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetStorageSpaceLevelsPagedCompletedEventHandler(object sender, GetStorageSpaceLevelsPagedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStorageSpaceLevelsPagedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStorageSpaceLevelsPagedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StorageSpaceLevelPaged Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StorageSpaceLevelPaged)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetStorageSpaceLevelByIdCompletedEventHandler(object sender, GetStorageSpaceLevelByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStorageSpaceLevelByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStorageSpaceLevelByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StorageSpaceLevel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StorageSpaceLevel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void SaveStorageSpaceLevelCompletedEventHandler(object sender, SaveStorageSpaceLevelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveStorageSpaceLevelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveStorageSpaceLevelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IntResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IntResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetLevelResourceGroupsCompletedEventHandler(object sender, GetLevelResourceGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLevelResourceGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLevelResourceGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResourceGroupInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResourceGroupInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void SaveLevelResourceGroupsCompletedEventHandler(object sender, SaveLevelResourceGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveLevelResourceGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveLevelResourceGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultObject)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void RemoveStorageSpaceLevelCompletedEventHandler(object sender, RemoveStorageSpaceLevelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveStorageSpaceLevelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveStorageSpaceLevelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultObject)(this.results[0]));
            }
        }
    }
}
